import { Inter } from "next/font/google";
import "../../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Login",
  description: "Generated by create next app",
};

export default function AdminLoginLayout({ children }) {
  return <div>{children}</div>;
}
