import Header from "app/components/Header";
import Footer from "app/components/Footer";

export const metadata = {
  title: "My Wishlists",
  description: "Generated by create next app",
};

export default function WishListLayout({ children }) {
  return (
    <div>
      <Header />
      <section className="bg-white py-8 antialiased dark:bg-gray-900 md:py-16">
        <div className="mx-auto max-w-screen-xl px-4 2xl:px-0">{children}</div>
      </section>
      <Footer />
    </div>
  );
}
