import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

// export async function generateMetadata({ params, searchParams }, parent) {
//   const slug = params.slug;

//   const product = await fetch(
//     `http://localhost:4000/api/products/${slug}`
//   ).then((res) => res.json());

//   return {
//     title: product.name,
//   };
// }
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
