import "../globals.css";

export const metadata = {
  title: "User",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return <div>{children}</div>;
}
